name: Run Python Script

on:
  push:
    branches:
      - main  # Runs only when pushing to main

jobs:
  run-python:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set powershell execution policy
        run: |
          Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Bypass -Force
        shell: pwsh

      - name: Get powershell execution policy
        run: |
          Get-ExecutionPolicy -l
        shell: pwsh


      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          if (Test-Path requirements.txt) {pip install -r requirements.txt}

      - name: Run Python Script
        run: python test1.py  # Replace with your Python file name

      - name: Un-set powershell execution policy
        run: |
          Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy RemoteSigned -Force
        shell: pwsh
