name: Run Python Script
on: [push]  # Runs when code is pushed

on:
  push:
    branches:
      - main  # Runs only when pushing to main
  pull_request:
    branches:
      - main  # Runs only for PRs targeting main
jobs:
  run-python:
    runs-on: bob_runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        run: python test1.py  # Replace with your Python file name
